[theme]
base="light"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FFFFFF"
textColor="#000000"
primaryColor="#ffffff"

[server]
# 런팟용 설정
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
headless = false

[browser]
gatherUsageStats = false

[global]
# 마크다운 해석 비활성화
disableWatchdogWarning = true